[fxrecorder]
host = "127.0.0.1:8888"

[fxrecorder.recording]
ffmpeg_path = "C:\\ffmpeg\\ffmpeg.exe"
video_size = { x = 1920, y = 1080 }
output_size = { x = 1366, y = 768 }
frame_rate = 60
device = "AVerMedia GC551 Video Capture"
buffer_size = "1000M"
minimum_recording_time_secs = 90

[fxrunner]
host = "0.0.0.0:8888"
session_dir = "C:\\fxrunner\\sessions"
display_size = { x = 1366, y = 768 }
