[package]
name = "fxrecorder"
version = "0.1.0"
authors = ["Barret Rennie <barret@mozilla.com>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
derive_more = "0.15.0"
libfxrecord = { path = "../libfxrecord" }
serde = { version = "1.0.100", features = ["derive"] }
slog = "2.5.2"
slog-async = "2.3.0"
slog-term = "2.4.1"
structopt = "0.3.1"
toml = "0.5.3"
