[fxrecorder]
host = "fxrunner01.corp.tor1.mozilla.com:8888"
visual_metrics_path = "C:\\fxrecorder\\fxrecord.toml"

[fxrecorder.recording]
video_size = { x = 1920, y = 1080 }
output_size = { x = 1366, y = 768 }
frame_rate = 60
device = "Game Capture HD60 S"
buffer_size = "1000M"
minimum_recording_time_secs = 60
