[package]
name = "integration-tests"
version = "0.1.0"
authors = ["barret Rennie <barret@mozilla.com>"]
edition = "2018"
license = "MPL-2.0"

[[test]]
name = "integration-tests"
path = "src/test.rs"

[dev-dependencies]
slog = "2.5.2"
tokio = "0.2.0-alpha.6"

[dev-dependencies.fxrecorder]
path = "../fxrecorder"

[dev-dependencies.fxrunner]
path = "../fxrunner"
